{% set name = "html5lib" %}
{% set version = "0.999" %}
{% set sha256 = "c3887f7e2875d7666107fa8bee761ff95b9391acdcc7cd1b5fd57a23b5fbc49e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six >=1.9
    - webencodings

test:
  imports:
    - html5lib
    - html5lib.filters
    - html5lib.treeadapters
    - html5lib.treebuilders
    - html5lib.treewalkers

about:
  home: https://github.com/html5lib/html5lib-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'HTML parser based on the WHATWG HTML specification'

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
